version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
    links:
      - db_mysql
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  db_mysql:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: O92092Vcsv3
      MYSQL_DATABASE: db
      MYSQL_USER: alexander
      MYSQL_PASSWORD: i0R2$ze2
      HOST_CACHE: 0
    ports:
      - "3306:3306"
    volumes:
      - ./:/usr/db_mysql:/var/lib/mysql
