version: "3.8"

services:
  db_mysql:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: O92092Vcsv3
      MYSQL_DATABASE: db
      MYSQL_USER: alexander
      MYSQL_PASSWORD: i0R2$ze2
    ports:
        - "3306:3306"
    volumes:
      - ./db_mysql:/var/lib/mysql
